//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplyForNewScheme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplyForNewScheme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplyForNewScheme", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ८-अ खाता क्रमांक.
        /// </summary>
        internal static string Account_Number {
            get {
                return ResourceManager.GetString("Account_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाब.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाबीचा सांकेतांक.
        /// </summary>
        internal static string Activity_Code {
            get {
                return ResourceManager.GetString("Activity_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाब.
        /// </summary>
        internal static string Activity_Name {
            get {
                return ResourceManager.GetString("Activity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वाढवा.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to माझ्या दिलेली सर्व माहिती सत्य आहे..
        /// </summary>
        internal static string All_the_information {
            get {
                return ResourceManager.GetString("All_the_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निवडलेल्या ७/१२ क्षेत्रापैकी या घटकासाठी वापरण्यात येणारे क्षेत्र.
        /// </summary>
        internal static string Area_used_for_this_activety_from_Selected {
            get {
                return ResourceManager.GetString("Area_used_for_this_activety_from_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटकाविषयीच्या तपशीलाकडे परत जा.
        /// </summary>
        internal static string Back_To_Activety_Details {
            get {
                return ResourceManager.GetString("Back_To_Activety_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाबीकडे मागे जा.
        /// </summary>
        internal static string Back_To_Activity {
            get {
                return ResourceManager.GetString("Back_To_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बॅंक खाते क्र..
        /// </summary>
        internal static string BANK_Ac_NO {
            get {
                return ResourceManager.GetString("BANK_Ac_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बँकेची तपशील.
        /// </summary>
        internal static string Bank_Detail {
            get {
                return ResourceManager.GetString("Bank_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बॅंकेचे नाव.
        /// </summary>
        internal static string BANK_NAME {
            get {
                return ResourceManager.GetString("BANK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामान्य सबसिडी.
        /// </summary>
        internal static string Common_Subsidy {
            get {
                return ResourceManager.GetString("Common_Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटक.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटकाचे नाव.
        /// </summary>
        internal static string Component_Name {
            get {
                return ResourceManager.GetString("Component_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी पुढे चालू.
        /// </summary>
        internal static string Continue_to_Application {
            get {
                return ResourceManager.GetString("Continue_to_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तपशील.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नमूद केलेल्या घटकाची अंदाजित किंमत.
        /// </summary>
        internal static string Estimated_cost_of_the_activity_applied_for {
            get {
                return ResourceManager.GetString("Estimated_cost_of_the_activity_applied_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पाच्या मापदंदानुसार अपेक्षित आर्थिक सहाय्य.
        /// </summary>
        internal static string Expected_financial_assistance_as_per_the_cost_norms {
            get {
                return ResourceManager.GetString("Expected_financial_assistance_as_per_the_cost_norms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जदार उर्वरीत भाग--भांडवल कसे मिळवणार आहे?.
        /// </summary>
        internal static string How_would_the_applicant_arrange_for_the_balance_funds {
            get {
                return ResourceManager.GetString("How_would_the_applicant_arrange_for_the_balance_funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFSC सांकेतांक.
        /// </summary>
        internal static string IFSC_CODE {
            get {
                return ResourceManager.GetString("IFSC_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपरोक्त बाबीकरिता अर्थसहाय्यासाठी माझी निवड झाली  असल्यास, मी प्रकल्पासाठी लागू असलेल्या सर्व मार्गदर्शक सुचनांनुसार आणि प्रकल्प अधिका-यांच्या तांत्रिक देखरेखीखाली दिलेल्या कालमर्यादेत बाब पूर्ण करीन.
        /// </summary>
        internal static string If_I_am_selected_for_assistance_under {
            get {
                return ResourceManager.GetString("If_I_am_selected_for_assistance_under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Info6 {
            get {
                return ResourceManager.GetString("Info6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मला माहित आहे की, वरील 1 मध्ये नमूद केल्याप्रमाणे घटकातील बाबीविषयीचे कामकाज पूर्ण केल्यानंतरच मी अर्थसहाय्य मिळवण्यास पात्र आहे. मला हे देखील माहित आहे की,  मी उपरोक्त 1 मध्ये नमूद केल्यानुसाड़ कामकाज पूर्ण न केल्यास अर्थसहाय्यासाठी पात्र नाही..
        /// </summary>
        internal static string I_am_aware_that_I {
            get {
                return ResourceManager.GetString("I_am_aware_that_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मला याची जाणीव आहे की प्रकल्पांतर्गत लाभ मिळवण्यासाठी मी खोटी आणि / किंवा चुकीचे माहिती दिल्याचे आढळून आल्यास प्र व्य कक्षास माझा अर्ज रद्द करण्याचे किंवा दिलेले अर्थसहाय्य परत घेण्याचे अधिकार आहेत..
        /// </summary>
        internal static string I_am_aware_that_the {
            get {
                return ResourceManager.GetString("I_am_aware_that_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी खात्रीलायकरित्या सांगतो/ सांगते की, मी अर्ज केलेल्या बाबींसाठी शासनाच्या अन्य कोणत्याही योजनेतून लाभ घेतलेला नाही वा लाभ मिळण्यासाठी अर्ज केलेला नाही..
        /// </summary>
        internal static string I_confirm_that_I_have {
            get {
                return ResourceManager.GetString("I_confirm_that_I_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी घोषित करतो/करते की, मी प्रकल्पाच्या प्रतिनिधींना माझ्या शेताचे,  उपकरणांचे  आणि नोंदींचे निरीक्षण करण्यास परवानगी व सहकार्य करीन.  मी दिलेल्या कालावधीसाठी प्रकल्पाच्या घटाकमधून मला देण्यात आलेल्या वस्तूंची देखभाल देखील करेल.
        /// </summary>
        internal static string I_hereby_declare_that {
            get {
                return ResourceManager.GetString("I_hereby_declare_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमिनीबाबत सर्वसाधारण माहिती.
        /// </summary>
        internal static string Land_Detail {
            get {
                return ResourceManager.GetString("Land_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इतर तपशील.
        /// </summary>
        internal static string Other_Details {
            get {
                return ResourceManager.GetString("Other_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to असल्यास कृपया योजनेचे नाव, वर्ष, इ. बाबत माहिती द्यावी..
        /// </summary>
        internal static string Provide_details_thereof_including_year_amount_scheme_etc {
            get {
                return ResourceManager.GetString("Provide_details_thereof_including_year_amount_scheme_etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आवश्यक.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नानाजी देशमुख कृषि संजीवनी प्रकल्पा अंतर्गत योजना. आपला अनुप्रयोग मंजूरीसाठी प्रलंबित आहे..
        /// </summary>
        internal static string scheme_under_Nanaji_Deshmukh_Krishi_Sanjivani_Prakalp_Your_Application_is_pending_for_Approvals {
            get {
                return ResourceManager.GetString("scheme_under_Nanaji_Deshmukh_Krishi_Sanjivani_Prakalp_Your_Application_is_pending" +
                        "_for_Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एससी एसटी सबसिडी.
        /// </summary>
        internal static string SC_ST_Subsidy {
            get {
                return ResourceManager.GetString("SC_ST_Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यादीमधून प्रकल्पांतर्गत बाब शोधा.
        /// </summary>
        internal static string Search_Activity_from_list {
            get {
                return ResourceManager.GetString("Search_Activity_from_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्थसहाय्याबाबत तपशील.
        /// </summary>
        internal static string Subsidy_Details {
            get {
                return ResourceManager.GetString("Subsidy_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपघटक.
        /// </summary>
        internal static string Sub_Component {
            get {
                return ResourceManager.GetString("Sub_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपघटकाचे नाव.
        /// </summary>
        internal static string Sub_Component_Name {
            get {
                return ResourceManager.GetString("Sub_Component_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ७/१२ सर्वे क्रमांक.
        /// </summary>
        internal static string Survey_Number {
            get {
                return ResourceManager.GetString("Survey_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टर्म.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्वयंघोषणापत्र.
        /// </summary>
        internal static string Undertaking {
            get {
                return ResourceManager.GetString("Undertaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जदाराने किंवा त्याच्या कुटुंबातील सदस्यांनी यापूर्वी इतर योजनेतून या प्रकारच्या घटकाचा / बाबीचा लाभ घेतला आहे का?.
        /// </summary>
        internal static string Whether_the_applicant_or_his_family_member {
            get {
                return ResourceManager.GetString("Whether_the_applicant_or_his_family_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपला अर्ज यशस्वीरित्या सबमिट केला गेला आहे..
        /// </summary>
        internal static string Your_application_has_been_successfully_submitted {
            get {
                return ResourceManager.GetString("Your_application_has_been_successfully_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपण यशस्वीरित्या अर्ज केला आहे.
        /// </summary>
        internal static string You_have_successfully_applied_for {
            get {
                return ResourceManager.GetString("You_have_successfully_applied_for", resourceCulture);
            }
        }
    }
}
