//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FarmerRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FarmerRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FarmerRegistration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आधार क्रमांक.
        /// </summary>
        internal static string AADHAR_NUMBER {
            get {
                return ResourceManager.GetString("AADHAR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/12 जोडा.
        /// </summary>
        internal static string ADD_ {
            get {
                return ResourceManager.GetString("ADD_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ८ अ जोडा.
        /// </summary>
        internal static string ADD_8A {
            get {
                return ResourceManager.GetString("ADD_8A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गुंठे.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रमाणीकरण प्रकार.
        /// </summary>
        internal static string AUTHENTICATION_TYPE {
            get {
                return ResourceManager.GetString("AUTHENTICATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ८ अ खातेक्रमांक.
        /// </summary>
        internal static string A_KHATA_KRAMANK {
            get {
                return ResourceManager.GetString("A_KHATA_KRAMANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुलभूत माहिती.
        /// </summary>
        internal static string BASIC_DETAILS {
            get {
                return ResourceManager.GetString("BASIC_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संवर्ग.
        /// </summary>
        internal static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गावसमुह क्र..
        /// </summary>
        internal static string CLUSTER_CODE {
            get {
                return ResourceManager.GetString("CLUSTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुढे चालू .....
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जन्मतारीख.
        /// </summary>
        internal static string DATE_OF_BIRTH {
            get {
                return ResourceManager.GetString("DATE_OF_BIRTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्वयंघोषणापत्र.
        /// </summary>
        internal static string DECLARATION {
            get {
                return ResourceManager.GetString("DECLARATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अपंगत्वाचे प्रमाण.
        /// </summary>
        internal static string DISABILITY_PERCENTAGE {
            get {
                return ResourceManager.GetString("DISABILITY_PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अपंगत्वाचे प्रमाण 40 टक्के किंवा त्यापेक्षा अधिक असल्याबाबतचे सक्षम प्राधिक-याचे प्रमाणपत्र (कृपया शासकीय रुग्णालयातील शल्यविशारदकाचे प्रमाणपत्र जोडावे.).
        /// </summary>
        internal static string Disability_with_40_or_more_will_be_considered_for_scheme_benefit_Kindly_attached_certificate_from_Government_Medical_Practitioner_displaying_the_same {
            get {
                return ResourceManager.GetString("Disability_with_40_or_more_will_be_considered_for_scheme_benefit_Kindly_attached_" +
                        "certificate_from_Government_Medical_Practitioner_displaying_the_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जिल्हा.
        /// </summary>
        internal static string DISTRICT {
            get {
                return ResourceManager.GetString("DISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इ-मेल पत्ता.
        /// </summary>
        internal static string EMAILID {
            get {
                return ResourceManager.GetString("EMAILID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ७/१२ उतारा.
        /// </summary>
        internal static string Extracts {
            get {
                return ResourceManager.GetString("Extracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेतकरी नोंदणी.
        /// </summary>
        internal static string Farmer_Registration {
            get {
                return ResourceManager.GetString("Farmer_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ८ अ (खाते उतारा).
        /// </summary>
        internal static string FORM_8_A {
            get {
                return ResourceManager.GetString("FORM_8_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लिंगभाव.
        /// </summary>
        internal static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हेक्टर.
        /// </summary>
        internal static string Hectare {
            get {
                return ResourceManager.GetString("Hectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घर क्र..
        /// </summary>
        internal static string HOUSE_NO {
            get {
                return ResourceManager.GetString("HOUSE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आधार क्रमांक नसल्यास नोंदणीसाठी येथे click करा..
        /// </summary>
        internal static string if_you_dont_have_an_aadhaar_number_please_click_here_to_enroll {
            get {
                return ResourceManager.GetString("if_you_dont_have_an_aadhaar_number_please_click_here_to_enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मला माझ्या भ्रमणध्वनी द्वारे प्रस्तुत प्रकल्पाची माहिती मिळणेकामी मी माझी सहमती देत आहे..
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी, उक्तप्रमाणे अर्जामध्ये माझा आधार क्रमांक दिलेला आह. मी, माझ्या आधार कार्डावरील माझा क्रमांक, नाव, हाताचे ठसे/ डॊळ्याची प्रतिकृति याचा वापर युआईडीएआई या संस्थेसमावेत माझी ओळख पटविण्यासाठी करण्यास प्रकल्प व्यवस्थापन कक्ष, नानाजी देशमुख कृषि संजीवनी प्रकल्प यांना करू देण्यास सहमती दर्शवीत आहे. प्रकल्प व्यवस्थापन कक्ष, नानाजी देशमुख कृषि संजीवनी प्रकल्प यांनी मला कळविले आहे की माझी ओळख पटविणारी माहिती फक्त प्रस्तूत प्रकल्पांतर्गत राबविण्यात येणारे उपक्रम आणि बाबी यासाठीच वापरली जाईल आणि माझ्या बायोमेट्रिक्स [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी माझ्या जमिनाधारणेबाबतची सर्व माहिती पूर्णत: भरलेली आहे..
        /// </summary>
        internal static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी दिलेली सर्व माहिती ही खरी व बरोबर असल्याची माझी पूर्ण खात्री आहे..
        /// </summary>
        internal static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to माझा भ्रमणध्वनी प्रस्तुत प्रकल्पाविषयी पत्रव्यवहार करण्यासाठी वापरणेस मी अनुमती देत आहे..
        /// </summary>
        internal static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मला हे जाणीव आहे कि, पोकरा ची निधी माझ्या &apos;आधार&apos;शी निगडित बँक खात्यात जमा केली जाईल..
        /// </summary>
        internal static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दुरध्वनी क्र..
        /// </summary>
        internal static string LANDLINE_NO {
            get {
                return ResourceManager.GetString("LANDLINE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमीन विवरण.
        /// </summary>
        internal static string LAND_DETAILS {
            get {
                return ResourceManager.GetString("LAND_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमीनधारणा.
        /// </summary>
        internal static string Land_Status {
            get {
                return ResourceManager.GetString("Land_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाईल क्र. - १.
        /// </summary>
        internal static string MOBILE_1 {
            get {
                return ResourceManager.GetString("MOBILE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाईल क्र. - २.
        /// </summary>
        internal static string MOBILE_2 {
            get {
                return ResourceManager.GetString("MOBILE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाव.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पॅन क्र.
        /// </summary>
        internal static string PANNO {
            get {
                return ResourceManager.GetString("PANNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आधार कार्डनुसार फोटो.
        /// </summary>
        internal static string Photo_as_on_Aadhar_Card {
            get {
                return ResourceManager.GetString("Photo_as_on_Aadhar_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दिव्यांग.
        /// </summary>
        internal static string PHYSICALLY_HANDICAP {
            get {
                return ResourceManager.GetString("PHYSICALLY_HANDICAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन कोड.
        /// </summary>
        internal static string PIN_CODE {
            get {
                return ResourceManager.GetString("PIN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पोस्ट.
        /// </summary>
        internal static string POST {
            get {
                return ResourceManager.GetString("POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मागील.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी तपशील.
        /// </summary>
        internal static string REGISTRATION_DETAILS {
            get {
                return ResourceManager.GetString("REGISTRATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ओटीपी पाठवा.
        /// </summary>
        internal static string SEND_OTP {
            get {
                return ResourceManager.GetString("SEND_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रस्ता क्र..
        /// </summary>
        internal static string STREET_NO {
            get {
                return ResourceManager.GetString("STREET_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदवा.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ७/१२ सर्वे क्रमांक.
        /// </summary>
        internal static string SURVEY_NUMBER {
            get {
                return ResourceManager.GetString("SURVEY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तालुका.
        /// </summary>
        internal static string TALUKA {
            get {
                return ResourceManager.GetString("TALUKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रमाणपत्र अपलोड करा.
        /// </summary>
        internal static string UPLOAD_CERITIFICATE {
            get {
                return ResourceManager.GetString("UPLOAD_CERITIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गावाचे नाव.
        /// </summary>
        internal static string VILLAGE {
            get {
                return ResourceManager.GetString("VILLAGE", resourceCulture);
            }
        }
    }
}
