//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SanctionDesk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SanctionDesk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SanctionDesk", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाब.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्रियाकलाप श्रेणी.
        /// </summary>
        internal static string Activity_Category {
            get {
                return ResourceManager.GetString("Activity_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाबीचा सांकेतांक.
        /// </summary>
        internal static string Activity_Code {
            get {
                return ResourceManager.GetString("Activity_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाब.
        /// </summary>
        internal static string Activity_Name {
            get {
                return ResourceManager.GetString("Activity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता द्वारे.
        /// </summary>
        internal static string AddressBy {
            get {
                return ResourceManager.GetString("AddressBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to देय रक्कम.
        /// </summary>
        internal static string amount_paid_upto {
            get {
                return ResourceManager.GetString("amount_paid_upto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जदाराचे नाव.
        /// </summary>
        internal static string Applicant_Name {
            get {
                return ResourceManager.GetString("Applicant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्ज तपशील.
        /// </summary>
        internal static string ApplicationDetails {
            get {
                return ResourceManager.GetString("ApplicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जांची यादी.
        /// </summary>
        internal static string Application_List {
            get {
                return ResourceManager.GetString("Application_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्ज क्रमांक.
        /// </summary>
        internal static string Application_No {
            get {
                return ResourceManager.GetString("Application_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनुप्रयोग स्थिती.
        /// </summary>
        internal static string Application_Status {
            get {
                return ResourceManager.GetString("Application_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजूरीचा.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजूरी लॉग.
        /// </summary>
        internal static string Approval_Log {
            get {
                return ResourceManager.GetString("Approval_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जाची सद्यस्थिती.
        /// </summary>
        internal static string App_Status {
            get {
                return ResourceManager.GetString("App_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यांना नियुक्त करा.
        /// </summary>
        internal static string Assign_To {
            get {
                return ResourceManager.GetString("Assign_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचा-यांना नियुक्त करा (पर्यायी).
        /// </summary>
        internal static string Assign_to_employee_Optional {
            get {
                return ResourceManager.GetString("Assign_to_employee_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्टेज परत.
        /// </summary>
        internal static string Back_To_Stage {
            get {
                return ResourceManager.GetString("Back_To_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शिल्लक रक्कम.
        /// </summary>
        internal static string Balance_Amount {
            get {
                return ResourceManager.GetString("Balance_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाभार्थी खर्च दावा केला.
        /// </summary>
        internal static string Beneficiary_Expense_Claimed {
            get {
                return ResourceManager.GetString("Beneficiary_Expense_Claimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाभार्थी प्रकार.
        /// </summary>
        internal static string Beneficiary_Type {
            get {
                return ResourceManager.GetString("Beneficiary_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बंद.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटक.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटकाचे नाव.
        /// </summary>
        internal static string Component_Name {
            get {
                return ResourceManager.GetString("Component_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तारीख.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मीटरमध्ये समन्वय दरम्यान अंतर.
        /// </summary>
        internal static string Distance_between_Coordinates_in_Meters {
            get {
                return ResourceManager.GetString("Distance_between_Coordinates_in_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेअरींग शेअरींग प्रलंबित तयार करत आहे.
        /// </summary>
        internal static string Documents_Preparing_Sharing_Pending {
            get {
                return ResourceManager.GetString("Documents_Preparing_Sharing_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कागदपत्र तपशील.
        /// </summary>
        internal static string Document_Details {
            get {
                return ResourceManager.GetString("Document_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दस्तऐवज प्रकार.
        /// </summary>
        internal static string Document_Type {
            get {
                return ResourceManager.GetString("Document_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कागदजत्र अपलोड केला.
        /// </summary>
        internal static string Document_Uploaded {
            get {
                return ResourceManager.GetString("Document_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाभार्थीद्वारे अपलोड केलेले दस्तऐवज.
        /// </summary>
        internal static string Document_Uploaded_by_beneficiary {
            get {
                return ResourceManager.GetString("Document_Uploaded_by_beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निरीक्षण अहवाल पत्रक डाउनलोड करा.
        /// </summary>
        internal static string Download_Inspection_Report_Sheet {
            get {
                return ResourceManager.GetString("Download_Inspection_Report_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्यवहार्यता अहवाल.
        /// </summary>
        internal static string Feasibility_Report {
            get {
                return ResourceManager.GetString("Feasibility_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जाच्या तारखेपासून.
        /// </summary>
        internal static string from_application_date {
            get {
                return ResourceManager.GetString("from_application_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीपी कोड व्हीसीएमएमसी बैठक दिनांक.
        /// </summary>
        internal static string GP_Code_VCRMC_Meeting_Date {
            get {
                return ResourceManager.GetString("GP_Code_VCRMC_Meeting_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध मापदंड लपवा.
        /// </summary>
        internal static string Hide_Search_Criteria {
            get {
                return ResourceManager.GetString("Hide_Search_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पदानुक्रम.
        /// </summary>
        internal static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तपासणी अहवाल.
        /// </summary>
        internal static string Inspection_report {
            get {
                return ResourceManager.GetString("Inspection_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निरीक्षक रक्कम शिफारसीय.
        /// </summary>
        internal static string Inspector_recommend_amount {
            get {
                return ResourceManager.GetString("Inspector_recommend_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमीन पत्ता.
        /// </summary>
        internal static string Land_Address {
            get {
                return ResourceManager.GetString("Land_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एचटीसी मध्ये जमीन.
        /// </summary>
        internal static string Land_in_HTC {
            get {
                return ResourceManager.GetString("Land_in_HTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्तर.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थान नकाशा.
        /// </summary>
        internal static string Location_Map {
            get {
                return ResourceManager.GetString("Location_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कमाल अनुमती रक्कम.
        /// </summary>
        internal static string Max_Allowed_amount {
            get {
                return ResourceManager.GetString("Max_Allowed_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाव.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पर्यंत दिले.
        /// </summary>
        internal static string paid_Upto {
            get {
                return ResourceManager.GetString("paid_Upto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पेमेंट व्यवहार्यता.
        /// </summary>
        internal static string Payment_Feasibility {
            get {
                return ResourceManager.GetString("Payment_Feasibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबदला मिळणेसाठी विनंती केलेली तारीख.
        /// </summary>
        internal static string Payment_Request_Date {
            get {
                return ResourceManager.GetString("Payment_Request_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबदला मिळणेसाठी विनंती क्रमांक.
        /// </summary>
        internal static string Payment_Request_No {
            get {
                return ResourceManager.GetString("Payment_Request_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पैसे भरल्याची स्थिती.
        /// </summary>
        internal static string Payment_Status {
            get {
                return ResourceManager.GetString("Payment_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to छायाचित्र.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्री मंजूरी डेस्क 1 प्रलंबित.
        /// </summary>
        internal static string Pre_Sanction_Desk_1_Pending {
            get {
                return ResourceManager.GetString("Pre_Sanction_Desk_1_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्री मंजूरी डेस्क 2 प्रलंबित.
        /// </summary>
        internal static string Pre_Sanction_Desk_2_Pending {
            get {
                return ResourceManager.GetString("Pre_Sanction_Desk_2_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्री मंजूरी डेस्क 3 प्रलंबित.
        /// </summary>
        internal static string Pre_Sanction_Desk_3_Pending {
            get {
                return ResourceManager.GetString("Pre_Sanction_Desk_3_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पूर्व मंजुरी पत्र.
        /// </summary>
        internal static string Pre_Sanction_Letter {
            get {
                return ResourceManager.GetString("Pre_Sanction_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कारण.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to म्हणून नोंदणीकृत.
        /// </summary>
        internal static string Register_As {
            get {
                return ResourceManager.GetString("Register_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी तपशील.
        /// </summary>
        internal static string RegistrationDetails {
            get {
                return ResourceManager.GetString("RegistrationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेता.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काहीही असल्यास टिप्पणी द्या.
        /// </summary>
        internal static string Remark_If_any {
            get {
                return ResourceManager.GetString("Remark_If_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रीसेट करा.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजूरी रक्कम.
        /// </summary>
        internal static string Sanction_Amount {
            get {
                return ResourceManager.GetString("Sanction_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजुरी डेस्क 5 प्रलंबित.
        /// </summary>
        internal static string Sanction_Desk_5_Pending {
            get {
                return ResourceManager.GetString("Sanction_Desk_5_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजुरी डेस्क 6 प्रलंबित.
        /// </summary>
        internal static string Sanction_Desk_6_Pending {
            get {
                return ResourceManager.GetString("Sanction_Desk_6_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निवडा.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध मापदंड दर्शवा.
        /// </summary>
        internal static string Show_Search_Criteria {
            get {
                return ResourceManager.GetString("Show_Search_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनुक्रमांक.
        /// </summary>
        internal static string Sr_No {
            get {
                return ResourceManager.GetString("Sr_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टप्पा.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपघटक.
        /// </summary>
        internal static string Sub_Component {
            get {
                return ResourceManager.GetString("Sub_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शीर्षक.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्ज करण्याच्या तारखेपर्यंत.
        /// </summary>
        internal static string to_application_date {
            get {
                return ResourceManager.GetString("to_application_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अद्यतन.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अद्ययावत.
        /// </summary>
        internal static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अपलोड केलेली प्रतिमा.
        /// </summary>
        internal static string Uploaded_Image {
            get {
                return ResourceManager.GetString("Uploaded_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अपलोड तपासणी तपशील.
        /// </summary>
        internal static string Uploaded_Inspection_Details {
            get {
                return ResourceManager.GetString("Uploaded_Inspection_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्हीसीएमसी बैठक.
        /// </summary>
        internal static string VCRMC_Meeting {
            get {
                return ResourceManager.GetString("VCRMC_Meeting", resourceCulture);
            }
        }
    }
}
