//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to समुदाय.
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेतकरी.
        /// </summary>
        internal static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एफपीओ / एफपीसी / एफआयजी / एसएचजी.
        /// </summary>
        internal static string FPO {
            get {
                return ResourceManager.GetString("FPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to महाराष्ट्र राज्याच्या 15 जिल्ह्यांत ग्रामपंचायतीच्या स्तरावर समुदाय स्थापित.
        /// </summary>
        internal static string Home_Comu {
            get {
                return ResourceManager.GetString("Home_Comu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to योजनेसाठी महाराष्ट्र राज्याच्या 15 जिल्ह्यांमध्ये जमीन असलेल्या शेतक-यांना.
        /// </summary>
        internal static string Home_Farmer {
            get {
                return ResourceManager.GetString("Home_Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoCRA कार्यालयाशी संबंधित अधिकारी.
        /// </summary>
        internal static string Home_Office {
            get {
                return ResourceManager.GetString("Home_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दुर्लक्षित शेतकर्यांच्या उत्थानसाठी महाराष्ट्र राज्याच्या 15 जिल्ह्यांमध्ये काम करणारे गट.
        /// </summary>
        internal static string Home_Others {
            get {
                return ResourceManager.GetString("Home_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डीबीटी-PoCRA मध्ये आपले स्वागत आहे.
        /// </summary>
        internal static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग इन.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अधिकारी.
        /// </summary>
        internal static string Officials {
            get {
                return ResourceManager.GetString("Officials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी करा.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
    }
}
