//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserManagement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आधार क्रमांक.
        /// </summary>
        internal static string Aadhar_No {
            get {
                return ResourceManager.GetString("Aadhar_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आधार क्रमांक.
        /// </summary>
        internal static string AADHAR_NUMBER {
            get {
                return ResourceManager.GetString("AADHAR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाब.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्रियाकलाप श्रेणी.
        /// </summary>
        internal static string Activity_Category {
            get {
                return ResourceManager.GetString("Activity_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाबीचा सांकेतांक.
        /// </summary>
        internal static string Activity_Code {
            get {
                return ResourceManager.GetString("Activity_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटक पात्रता यादी.
        /// </summary>
        internal static string Activity_Eligibility_List {
            get {
                return ResourceManager.GetString("Activity_Eligibility_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटक प्रतिमा (325 X 325 PX).
        /// </summary>
        internal static string Activity_Image {
            get {
                return ResourceManager.GetString("Activity_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटकांची पूर्ण यादी.
        /// </summary>
        internal static string Activity_Master_List {
            get {
                return ResourceManager.GetString("Activity_Master_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाब.
        /// </summary>
        internal static string Activity_Name {
            get {
                return ResourceManager.GetString("Activity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाब (मराठी).
        /// </summary>
        internal static string Activity_Name_marathi {
            get {
                return ResourceManager.GetString("Activity_Name_marathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटकाबाबत सद्यस्थिती.
        /// </summary>
        internal static string Activity_Status {
            get {
                return ResourceManager.GetString("Activity_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता आणि इतर तपशील.
        /// </summary>
        internal static string ADDRESS_AND_OTHER_DETAILS {
            get {
                return ResourceManager.GetString("ADDRESS_AND_OTHER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी दिलेली सर्व माहिती ही खरी व बरोबर असल्याची माझी पूर्ण खात्री आहे..
        /// </summary>
        internal static string All_the_information {
            get {
                return ResourceManager.GetString("All_the_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी ग्राम कृषि संजीवनी समितीच्या वतीने दिलेली  सर्व माहिती सत्य आणि योग्य आहे..
        /// </summary>
        internal static string All_the_information1 {
            get {
                return ResourceManager.GetString("All_the_information1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API अधिकृत यादी.
        /// </summary>
        internal static string API_Authorized_List {
            get {
                return ResourceManager.GetString("API_Authorized_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जांची यादी.
        /// </summary>
        internal static string Application_List {
            get {
                return ResourceManager.GetString("Application_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जाची सद्यस्थिती.
        /// </summary>
        internal static string Application_Status {
            get {
                return ResourceManager.GetString("Application_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजूरीचा टप्पा.
        /// </summary>
        internal static string Approval_Stages {
            get {
                return ResourceManager.GetString("Approval_Stages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नेमून दिलेले कामकाज.
        /// </summary>
        internal static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बँक खात्याची नोंदणी करण्याच्या वेळी, वापरकर्त्याने टी अँड सी स्वीकारणे &quot;मी समजतो की आधार आधारित वितरण माझ्या आधार लिंक बँक खात्यात जमा केले जाईल&quot;.
        /// </summary>
        internal static string At_the_time_of_registering {
            get {
                return ResourceManager.GetString("At_the_time_of_registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बँक खात्याची नोंदणी करताना, वापरकर्त्याने टी &amp; सी स्वीकारणे &quot;मला समजले की वितरणास समुदायाच्या नोंदणीकृत बँक खात्यात जमा केले जाईल&quot;.
        /// </summary>
        internal static string At_the_time_of_registering_Bank_Account {
            get {
                return ResourceManager.GetString("At_the_time_of_registering_Bank_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अधिकृत व्यक्ती ई - मेल आयडी.
        /// </summary>
        internal static string AUTHORISED_PERSON_EMAILID {
            get {
                return ResourceManager.GetString("AUTHORISED_PERSON_EMAILID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्राधिकृत व्यक्तीचे नाव.
        /// </summary>
        internal static string AUTHORISED_PERSON_MOBILE {
            get {
                return ResourceManager.GetString("AUTHORISED_PERSON_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्राधिकृत व्यक्तीचे नाव.
        /// </summary>
        internal static string AUTHORISED_PERSON_NAME {
            get {
                return ResourceManager.GetString("AUTHORISED_PERSON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुलभूत माहिती.
        /// </summary>
        internal static string BASIC_DETAILS {
            get {
                return ResourceManager.GetString("BASIC_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाभार्थी प्रकार.
        /// </summary>
        internal static string Beneficiary_Types {
            get {
                return ResourceManager.GetString("Beneficiary_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाभार्थी प्रकार.
        /// </summary>
        internal static string Benificiary_Type {
            get {
                return ResourceManager.GetString("Benificiary_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to श्रेणी.
        /// </summary>
        internal static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुख्य कार्यकारी अधिकारी/ सचिव.
        /// </summary>
        internal static string CEO_SECRETARY {
            get {
                return ResourceManager.GetString("CEO_SECRETARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंडळ.
        /// </summary>
        internal static string CIRCLE {
            get {
                return ResourceManager.GetString("CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गावसमुह.
        /// </summary>
        internal static string CLUSTER {
            get {
                return ResourceManager.GetString("CLUSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गावसमुह क्र..
        /// </summary>
        internal static string CLUSTER_CODE {
            get {
                return ResourceManager.GetString("CLUSTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामान्य सबसिडी.
        /// </summary>
        internal static string Common_Subsidy {
            get {
                return ResourceManager.GetString("Common_Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामान्य सबसिडी रक्कम.
        /// </summary>
        internal static string Common_Subsidy_Amount {
            get {
                return ResourceManager.GetString("Common_Subsidy_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्राम कृषि संजीवनी समिती नोंदणी यादी.
        /// </summary>
        internal static string Community_Registration_List {
            get {
                return ResourceManager.GetString("Community_Registration_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटक.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्रव्यवहाराचा पत्ता.
        /// </summary>
        internal static string CORRESPONDENCE_ADDRESS {
            get {
                return ResourceManager.GetString("CORRESPONDENCE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वर्तमान स्थिती.
        /// </summary>
        internal static string Current_Status {
            get {
                return ResourceManager.GetString("Current_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तारीख.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जन्मतारीख.
        /// </summary>
        internal static string DATE_OF_BIRTH {
            get {
                return ResourceManager.GetString("DATE_OF_BIRTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घोषणापत्र.
        /// </summary>
        internal static string DECLARATION {
            get {
                return ResourceManager.GetString("DECLARATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्वयंघोषणापत्र.
        /// </summary>
        internal static string Declarations {
            get {
                return ResourceManager.GetString("Declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डिलीट करा.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पदनाम.
        /// </summary>
        internal static string DESIGNATION {
            get {
                return ResourceManager.GetString("DESIGNATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अपंगत्वाचे प्रमाण.
        /// </summary>
        internal static string DISABILITY_PERCENTAGE {
            get {
                return ResourceManager.GetString("DISABILITY_PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जिल्हा.
        /// </summary>
        internal static string DISTRICT {
            get {
                return ResourceManager.GetString("DISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आवश्यक कागदपत्र.
        /// </summary>
        internal static string Document_Required {
            get {
                return ResourceManager.GetString("Document_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वापरकर्त्याची पासपोर्ट आकाराचा फ़ोटो जोडा जोडा.
        /// </summary>
        internal static string Drop_A_passport_size_image_of_user {
            get {
                return ResourceManager.GetString("Drop_A_passport_size_image_of_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आवश्यक पात्रता.
        /// </summary>
        internal static string Eligibility_Criteria {
            get {
                return ResourceManager.GetString("Eligibility_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इ-मेल पत्ता.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इ-मेल पत्ता.
        /// </summary>
        internal static string EMAIL_ID {
            get {
                return ResourceManager.GetString("EMAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेतकरी नाव .
        /// </summary>
        internal static string FARMER_NAME {
            get {
                return ResourceManager.GetString("FARMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेतकरी नोंदणी यादी.
        /// </summary>
        internal static string Farmer_Registration_List {
            get {
                return ResourceManager.GetString("Farmer_Registration_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्यवहार्यता अहवाल.
        /// </summary>
        internal static string Feasibility_Report {
            get {
                return ResourceManager.GetString("Feasibility_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेतकरी उत्पादक संघ / शेतकरी उत्पादक कंपनी / शेतकरी उत्पादक गट / बचत गट नोंदणी यादी.
        /// </summary>
        internal static string FPO_Registration_List {
            get {
                return ResourceManager.GetString("FPO_Registration_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जाच्या तारखेपासून.
        /// </summary>
        internal static string From_Application_Date {
            get {
                return ResourceManager.GetString("From_Application_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी तारखेपासून.
        /// </summary>
        internal static string FROM_REGISTRATION_DATE {
            get {
                return ResourceManager.GetString("FROM_REGISTRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पूर्ण नाव.
        /// </summary>
        internal static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लिंगभाव.
        /// </summary>
        internal static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्रामपंचायत कोड.
        /// </summary>
        internal static string GramPanchayatCode {
            get {
                return ResourceManager.GetString("GramPanchayatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्गदर्शक तत्वे.
        /// </summary>
        internal static string Guideline_Document {
            get {
                return ResourceManager.GetString("Guideline_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पदानुक्रम.
        /// </summary>
        internal static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पदानुक्रम कोड.
        /// </summary>
        internal static string Hierarchy_Code {
            get {
                return ResourceManager.GetString("Hierarchy_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पदानुक्रम नाव.
        /// </summary>
        internal static string Hierarchy_Name {
            get {
                return ResourceManager.GetString("Hierarchy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घर क्र..
        /// </summary>
        internal static string HOUSE_NO {
            get {
                return ResourceManager.GetString("HOUSE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निरीक्षण फॉर्म प्रकार.
        /// </summary>
        internal static string Inspection_Forms_Type {
            get {
                return ResourceManager.GetString("Inspection_Forms_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जर मोबाईल नंबर जोडलेला नसेल तर &quot;आपला क्रमांक आधारेशी जोडलेला नाही&quot; असे सांगण्यास सिस्टमने पॉप अप देणे आवश्यक आहे. कृपया आपल्या मोबाइल क्रमांकासह आपला आधार लिंक करा आणि नंतर लॉग इन करण्याचा प्रयत्न करा किंवा बायोमेट्रिक लॉगिन निवडा आणि आधार केवायसी केंद्राकडून मदत घ्या &quot;.
        /// </summary>
        internal static string In_case_mobile_number {
            get {
                return ResourceManager.GetString("In_case_mobile_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी माझ्या जमिनाधारणेबाबतची सर्व माहिती पूर्णत: भरलेली आहे..
        /// </summary>
        internal static string I_confirm_that {
            get {
                return ResourceManager.GetString("I_confirm_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मला माझ्या भ्रमणध्वनी द्वारे प्रस्तुत प्रकल्पाची माहिती मिळणेकामी मी माझी सहमती देत आहे..
        /// </summary>
        internal static string I_hereby_consent {
            get {
                return ResourceManager.GetString("I_hereby_consent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मी, उक्तप्रमाणे अर्जामध्ये माझा आधार क्रमांक दिलेला आह. मी, माझ्या आधार कार्डावरील माझा क्रमांक, नाव, हाताचे ठसे/ डॊळ्याची प्रतिकृति याचा वापर युआईडीएआई या संस्थेसमावेत माझी ओळख पटविण्यासाठी करण्यास प्रकल्प व्यवस्थापन कक्ष, नानाजी देशमुख कृषि संजीवनी प्रकल्प यांना करू देण्यास सहमती दर्शवीत आहे. प्रकल्प व्यवस्थापन कक्ष, नानाजी देशमुख कृषि संजीवनी प्रकल्प यांनी मला कळविले आहे की माझी ओळख पटविणारी माहिती फक्त प्रस्तूत प्रकल्पांतर्गत राबविण्यात येणारे उपक्रम आणि बाबी यासाठीच वापरली जाईल आणि माझ्या बायोमेट्रिक्स [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I_the_holder_of_AADHAR {
            get {
                return ResourceManager.GetString("I_the_holder_of_AADHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दुरध्वनी क्र..
        /// </summary>
        internal static string LANDLINE_NO {
            get {
                return ResourceManager.GetString("LANDLINE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमीन विवरण.
        /// </summary>
        internal static string LAND_DETAILS {
            get {
                return ResourceManager.GetString("LAND_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमीन स्थिती.
        /// </summary>
        internal static string LAND_STATUS {
            get {
                return ResourceManager.GetString("LAND_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्तर.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पदरचना यादी.
        /// </summary>
        internal static string Level_Hierarchy_List {
            get {
                return ResourceManager.GetString("Level_Hierarchy_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाईल क्र..
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाईल क्र. - १.
        /// </summary>
        internal static string MOBILE1 {
            get {
                return ResourceManager.GetString("MOBILE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाईल क्र. - २.
        /// </summary>
        internal static string MOBILE2 {
            get {
                return ResourceManager.GetString("MOBILE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाव.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विकलांग व्यक्ती निवडीसाठी जोडल्या जाणार्या टीप &quot;40% किंवा अधिक असंगतता योजनेच्या फायद्यासाठी विचारात घेण्यात येईल. सरकारी वैद्यकीय प्रॅक्टिशनरकडून कृपया संलग्न केलेले प्रमाणपत्र त्याच &quot;.
        /// </summary>
        internal static string Note_to_be_added {
            get {
                return ResourceManager.GetString("Note_to_be_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संस्थेचे नाव.
        /// </summary>
        internal static string Organization_Name {
            get {
                return ResourceManager.GetString("Organization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इतर सेटिंग्ज.
        /// </summary>
        internal static string Other_Settings {
            get {
                return ResourceManager.GetString("Other_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पॅन क्र.
        /// </summary>
        internal static string PAN_NO {
            get {
                return ResourceManager.GetString("PAN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पालक पदक्रम.
        /// </summary>
        internal static string Parent_Hierarchy {
            get {
                return ResourceManager.GetString("Parent_Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासवर्ड.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्थसहाय्य देण्याची अट.
        /// </summary>
        internal static string Payment_Term {
            get {
                return ResourceManager.GetString("Payment_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दुरद्वनी क्रमांक.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दिव्यांग.
        /// </summary>
        internal static string PHYSICALLY_HANDICAP {
            get {
                return ResourceManager.GetString("PHYSICALLY_HANDICAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन कोड.
        /// </summary>
        internal static string PIN_CODE {
            get {
                return ResourceManager.GetString("PIN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पोस्ट.
        /// </summary>
        internal static string POST {
            get {
                return ResourceManager.GetString("POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पूर्व-संमती पत्र प्रकार.
        /// </summary>
        internal static string Pre_Sanction_letters_Type {
            get {
                return ResourceManager.GetString("Pre_Sanction_letters_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेतकरी गटाच्या (FPO/FPC/FIG/SHGs) प्रवर्तकाचा तपशील.
        /// </summary>
        internal static string PROMOTER_DETAILS {
            get {
                return ResourceManager.GetString("PROMOTER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्राधिकृत असल्याचा पुरावा.
        /// </summary>
        internal static string PROOF_OF_AUTHORISATION {
            get {
                return ResourceManager.GetString("PROOF_OF_AUTHORISATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कारण.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दस्तएवज / पृष्ठ क्र..
        /// </summary>
        internal static string Records_Page {
            get {
                return ResourceManager.GetString("Records_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणीकृत पत्ता.
        /// </summary>
        internal static string REGISTERED_ADDRESS {
            get {
                return ResourceManager.GetString("REGISTERED_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to याद्वारे नोंदणीकृत.
        /// </summary>
        internal static string REGISTERED_THROUGH {
            get {
                return ResourceManager.GetString("REGISTERED_THROUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to याअंतर्गत नोंदणीकृत.
        /// </summary>
        internal static string REGISTERED_UNDER {
            get {
                return ResourceManager.GetString("REGISTERED_UNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणीचे प्रमाणपत्र.
        /// </summary>
        internal static string REGISTRATION_CERTIFICATE {
            get {
                return ResourceManager.GetString("REGISTRATION_CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी दिनांक.
        /// </summary>
        internal static string REGISTRATION_DATE {
            get {
                return ResourceManager.GetString("REGISTRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी क्रमांक.
        /// </summary>
        internal static string Registration_No {
            get {
                return ResourceManager.GetString("Registration_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काहीही असल्यास टिप्पणी द्या.
        /// </summary>
        internal static string Remark_if_any {
            get {
                return ResourceManager.GetString("Remark_if_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आवश्यक जमीनधारणा.
        /// </summary>
        internal static string Required_Land {
            get {
                return ResourceManager.GetString("Required_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रीसेट करा.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्तव्य व जबाबदारी.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जतन करा.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एससी / एसटी सबसिडी.
        /// </summary>
        internal static string SC_ST_Subsidy {
            get {
                return ResourceManager.GetString("SC_ST_Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनु. जाती/जमातीतील लाभार्थांसाठी लागू असलेले अर्थसहाय्य.
        /// </summary>
        internal static string SC_ST_Subsidy_Amount {
            get {
                return ResourceManager.GetString("SC_ST_Subsidy_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध शब्द.
        /// </summary>
        internal static string Search_Term {
            get {
                return ResourceManager.GetString("Search_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हंगाम.
        /// </summary>
        internal static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कालमर्यादा निश्चित करा.
        /// </summary>
        internal static string Set_TimeLine {
            get {
                return ResourceManager.GetString("Set_TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टप्पे.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रस्ता क्र..
        /// </summary>
        internal static string STREET_NO {
            get {
                return ResourceManager.GetString("STREET_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्थसहाय्याविषयीची यादी.
        /// </summary>
        internal static string Subsidy_Term_List {
            get {
                return ResourceManager.GetString("Subsidy_Term_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपघटक.
        /// </summary>
        internal static string Sub_Component {
            get {
                return ResourceManager.GetString("Sub_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तालुका.
        /// </summary>
        internal static string TALUKA {
            get {
                return ResourceManager.GetString("TALUKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्ज करण्याच्या तारखेपर्यंत.
        /// </summary>
        internal static string To_Application_Date {
            get {
                return ResourceManager.GetString("To_Application_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्ज करण्याच्या तारखेपर्यंत.
        /// </summary>
        internal static string TO_REGISTRATION_DATE {
            get {
                return ResourceManager.GetString("TO_REGISTRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अद्यतन.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वापरकर्ता नाव.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वापरकर्त्यांची यादी.
        /// </summary>
        internal static string User_List {
            get {
                return ResourceManager.GetString("User_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पडताळणी.
        /// </summary>
        internal static string VERIFICATION {
            get {
                return ResourceManager.GetString("VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सत्यापन लॉग.
        /// </summary>
        internal static string VERIFICATION_LOG {
            get {
                return ResourceManager.GetString("VERIFICATION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गावाचे नाव.
        /// </summary>
        internal static string VILLAGE {
            get {
                return ResourceManager.GetString("VILLAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इतर व्यक्तीचा मोबाइल नंबर नोंदवताना, वापरकर्त्याने &quot;पीओसीआरए कडून संप्रेषणांसाठी दिलेल्या मोबाइल नंबरचा वापर करण्यास मी सहमत आहे&quot; असे नियम आणि अटी स्वीकारण्याचे प्रयोक्ता.
        /// </summary>
        internal static string While_registering_mobile_number {
            get {
                return ResourceManager.GetString("While_registering_mobile_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to महिलांकरिता लागू असलेल्या अर्थसहाय्याची टक्केवारी.
        /// </summary>
        internal static string Woman_Subsidy {
            get {
                return ResourceManager.GetString("Woman_Subsidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to महिलांकरिता लागू असलेले अर्थसहाय.
        /// </summary>
        internal static string Woman_Subsidy_Amount {
            get {
                return ResourceManager.GetString("Woman_Subsidy_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपण फाइल ब्राउजर उघडण्यासाठी देखील क्लिक करू शकता.
        /// </summary>
        internal static string You_can_also_click_to_open_file_browser {
            get {
                return ResourceManager.GetString("You_can_also_click_to_open_file_browser", resourceCulture);
            }
        }
    }
}
