//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserDashBord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserDashBord() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserDashBord", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाबीचा सांकेतांक.
        /// </summary>
        internal static string ActivityCode {
            get {
                return ResourceManager.GetString("ActivityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पांतर्गत बाब.
        /// </summary>
        internal static string ActivityName {
            get {
                return ResourceManager.GetString("ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जाची सद्यस्थिती.
        /// </summary>
        internal static string Application_Status {
            get {
                return ResourceManager.GetString("Application_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मंजूर रक्कम.
        /// </summary>
        internal static string Approved_Amount {
            get {
                return ResourceManager.GetString("Approved_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कामकाज पूर्ण झालेले अर्ज.
        /// </summary>
        internal static string CLOSED_APPLICATIONS {
            get {
                return ResourceManager.GetString("CLOSED_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटकाचे नाव.
        /// </summary>
        internal static string Component_Name {
            get {
                return ResourceManager.GetString("Component_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तारीख.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्तर.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to भ्रमणध्वनी क्र..
        /// </summary>
        internal static string MOBILE_NO {
            get {
                return ResourceManager.GetString("MOBILE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाव.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वरील सर्व बाबींची पूर्तता झालेनंतरच पुर्नतपासणी करण्याची परवानगी देण्यात येईल..
        /// </summary>
        internal static string Note_Re_verification_can_be_allowed_only_after_resolving_all_above_resions {
            get {
                return ResourceManager.GetString("Note_Re_verification_can_be_allowed_only_after_resolving_all_above_resions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभिलेख उपलब्ध नाही.
        /// </summary>
        internal static string No_Record_Found {
            get {
                return ResourceManager.GetString("No_Record_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नव्याने प्राप्त अर्ज.
        /// </summary>
        internal static string OPEN_APPLICATIONS {
            get {
                return ResourceManager.GetString("OPEN_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to देयक विनंती स्थिती.
        /// </summary>
        internal static string Payment_Request_Status {
            get {
                return ResourceManager.GetString("Payment_Request_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कारण.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी दिनांक.
        /// </summary>
        internal static string REGISTRATION_DATE {
            get {
                return ResourceManager.GetString("REGISTRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणी तपशील.
        /// </summary>
        internal static string REGISTRATION_DETAILS {
            get {
                return ResourceManager.GetString("REGISTRATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नोंदणीची सद्यस्थिती.
        /// </summary>
        internal static string REGISTRATION_STATUS {
            get {
                return ResourceManager.GetString("REGISTRATION_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेता.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विनंती रक्कम.
        /// </summary>
        internal static string Request_Amount {
            get {
                return ResourceManager.GetString("Request_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विनंती क्रमांक.
        /// </summary>
        internal static string Request_No {
            get {
                return ResourceManager.GetString("Request_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनुक्रमांक.
        /// </summary>
        internal static string Sr_No {
            get {
                return ResourceManager.GetString("Sr_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टप्पा.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टप्पे.
        /// </summary>
        internal static string Stages {
            get {
                return ResourceManager.GetString("Stages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Updated_By {
            get {
                return ResourceManager.GetString("Updated_By", resourceCulture);
            }
        }
    }
}
