//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VCRMCMeetingData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VCRMCMeetingData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.VCRMCMeetingData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाब.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्रियाकलाप श्रेणी.
        /// </summary>
        internal static string Activity_Category {
            get {
                return ResourceManager.GetString("Activity_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जांची यादी.
        /// </summary>
        internal static string Application_List {
            get {
                return ResourceManager.GetString("Application_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाभार्थी प्रकार.
        /// </summary>
        internal static string Beneficiary_Type {
            get {
                return ResourceManager.GetString("Beneficiary_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बंद.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घटक.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एक्सेलमध्ये पहाण्यासाठी.
        /// </summary>
        internal static string Export_To_Excel {
            get {
                return ResourceManager.GetString("Export_To_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्जाच्या तारखेपासून.
        /// </summary>
        internal static string From_Application_Date {
            get {
                return ResourceManager.GetString("From_Application_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीपी कोड .
        /// </summary>
        internal static string GP_Code {
            get {
                return ResourceManager.GetString("GP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बैठकीची तारीख.
        /// </summary>
        internal static string Meeting_Date {
            get {
                return ResourceManager.GetString("Meeting_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बैठकीचे इतिवृत्त.
        /// </summary>
        internal static string Minute_Of_meeting {
            get {
                return ResourceManager.GetString("Minute_Of_meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कोणताही रेकॉर्ड सापडला नाही.
        /// </summary>
        internal static string No_Record_Found {
            get {
                return ResourceManager.GetString("No_Record_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्हीसीएमसीच्या बैठकीची छायाचित्रे.
        /// </summary>
        internal static string Photographs_of_VCRMC_meeting {
            get {
                return ResourceManager.GetString("Photographs_of_VCRMC_meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया ब्राउझ करा आणि अपलोड करा.
        /// </summary>
        internal static string Please_Browse_and_upload {
            get {
                return ResourceManager.GetString("Please_Browse_and_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रीसेट करा.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जतन करा.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शोध मापदंड दर्शवा.
        /// </summary>
        internal static string Show_Search_Criteria {
            get {
                return ResourceManager.GetString("Show_Search_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपघटक.
        /// </summary>
        internal static string Sub_Component {
            get {
                return ResourceManager.GetString("Sub_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्ज करण्याच्या तारखेपर्यंत.
        /// </summary>
        internal static string To_Application_Date {
            get {
                return ResourceManager.GetString("To_Application_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अपलोड करा.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
